export const BASE_EXERCISES = [
  { id:"d1-01", type:"foundation", skill:"present_simple", reviewSkills:["frequency"], prompt:"我通常在放学后做作业。", focus:"Present Simple + frequency", hints:["usually 表示习惯，用一般现在时。","主语 I 后面用 do。","I + usually + do my homework + after school."], model:"I usually do my homework after school." },
  { id:"d1-02", type:"foundation", skill:"third_person", reviewSkills:["articles"], prompt:"我妹妹每天乘公共汽车去学校。", focus:"Third-person singular", hints:["my sister 相当于 she。","第三人称单数：take → takes。","My sister + takes the bus + to school + every day."], model:"My sister takes the bus to school every day." },
  { id:"d1-03", type:"foundation", skill:"past_simple", reviewSkills:[], prompt:"我们昨天在科学课上做了一个实验。", focus:"Past Simple", hints:["yesterday 表示过去。","do 的过去式是 did。","We + did an experiment + in science class + yesterday."], model:"We did an experiment in science class yesterday." },
  { id:"d1-04", type:"foundation", skill:"did_auxiliary", reviewSkills:["past_simple"], prompt:"老师昨天没有给我们家庭作业。", focus:"didn't + base verb", hints:["这是过去时否定句。","didn't 后必须用动词原形。","The teacher + didn't give + us homework + yesterday."], model:"The teacher didn't give us homework yesterday." },
  { id:"d1-05", type:"foundation", skill:"future", reviewSkills:[], prompt:"明天我们要在数学课上参加一个测验。", focus:"Future with will", hints:["tomorrow 表示将来。","will 后使用动词原形。","We + will + take a quiz + in math class + tomorrow."], model:"We will take a quiz in math class tomorrow." },
  { id:"d1-06", type:"foundation", skill:"singular_plural", reviewSkills:["be_verbs"], prompt:"这两本书都很有趣。", focus:"Plural subject + be", hints:["books 是复数。","复数主语搭配 are。","These two books + are + interesting."], model:"These two books are interesting." },
  { id:"d1-07", type:"mixed", skill:"because", reviewSkills:["third_person"], prompt:"我的朋友喜欢科学，因为他喜欢做实验。", focus:"because + third-person", hints:["because 后面说明原因。","my friend 和 he 都是第三人称单数。","My friend likes science because he likes doing experiments."], model:"My friend likes science because he likes doing experiments." },
  { id:"d1-08", type:"mixed", skill:"time_clauses", reviewSkills:["third_person"], prompt:"当老师提问时，我会先认真听。", focus:"When clause", hints:["when 表示“当……的时候”。","teacher 是第三人称单数：ask → asks。","When the teacher asks a question, I listen carefully first."], model:"When the teacher asks a question, I listen carefully first." },
  { id:"d1-09", type:"mixed", skill:"coordination", reviewSkills:["past_simple","be_verbs"], prompt:"我昨晚很累，所以我很早就睡觉了。", focus:"Past tense + so", hints:["last night 表示过去。","am → was；go → went。","I was tired last night, so I went to bed early."], model:"I was tired last night, so I went to bed early." },
  { id:"d1-10", type:"mixed", skill:"if_clause", reviewSkills:["present_simple"], prompt:"如果我不懂一个单词，我会查它的意思。", focus:"If clause", hints:["if 表示“如果”。","描述通常做法，两部分都用一般现在时。","If I don't understand a word, I look up its meaning."], model:"If I don't understand a word, I look up its meaning." },
  { id:"d1-11", type:"school_life", skill:"be_verbs", reviewSkills:["sentence_structure"], prompt:"我的 Chromebook 现在不在书包里。", focus:"Singular + be negative", hints:["Chromebook 是单数。","否定使用 is not / isn't。","My Chromebook isn't in my backpack now."], model:"My Chromebook isn't in my backpack now." },
  { id:"d1-12", type:"transfer", skill:"sentence_expansion", reviewSkills:["past_simple","coordination"], prompt:"上周我读了一本很有趣的书，而且我把它推荐给了朋友。", focus:"Past tense + connected idea", hints:["last week 表示过去。","两个相关动作可以用 and 连接。","Last week, I read an interesting book and recommended it to my friend."], model:"Last week, I read an interesting book and recommended it to my friend." }
];
