export const CURRICULUM_VERSION = 2;

export const CURRICULUM_STAGES = [
  {stage:1,title:"Sentence Foundations",goal:"Write complete, grammatically controlled simple sentences.",parentNoteZh:"先把最基本的完整句打牢：谁/什么 + 做什么/是什么 + 必要的名词、代词和冠词。这个阶段不追求复杂句。",advancement:"Every Stage 1 core skill needs at least 2 evidence records and mastery >= 75%.",promptMode:"Chinese prompt → one English sentence",sentenceMode:"1 sentence, usually 5–10 words",generationGuardrails:["Use everyday school/home vocabulary.","One main grammar target per item.","Avoid clauses unless the lesson explicitly asks for one.","Do not use rare idioms or phrasal verbs."]},
  {stage:2,title:"Present-Time Control",goal:"Describe routines, facts, and repeated actions accurately in the simple present.",parentNoteZh:"掌握一般现在时、第三人称单数、否定/疑问和频率表达。",advancement:"All Stage 2 skills need repeated independent evidence; keep earlier Stage 1 skills mixed in review.",promptMode:"Chinese prompt → one English sentence",sentenceMode:"1 sentence, usually 6–12 words",generationGuardrails:["Use clear present-time markers such as every day, usually, often.","Contrast I/you/we/they with he/she/it.","Keep vocabulary familiar and school-life centered."]},
  {stage:3,title:"Past-Time Control",goal:"Tell what happened in the past using correct past forms and auxiliaries.",parentNoteZh:"重点解决过去式、did/didn't 后动词原形、was/were 和常见不规则动词。",advancement:"Require independent control of past tense and did + base verb across new transfer sentences.",promptMode:"Chinese prompt → one English sentence",sentenceMode:"1 sentence, usually 6–13 words",generationGuardrails:["Include explicit past-time markers often.","Use common irregular verbs only at first.","Test did/didn't + base verb repeatedly with transfer sentences."]},
  {stage:4,title:"Future and Modal Meaning",goal:"Express plans, predictions, ability, advice, and obligation.",parentNoteZh:"学习 will / be going to 以及 can, should, must 等情态动词，强调情态动词后接动词原形。",advancement:"Future and modal forms must be stable in unfamiliar school and daily-life contexts.",promptMode:"Chinese prompt → one English sentence",sentenceMode:"1 sentence, usually 6–14 words",generationGuardrails:["Keep one future/modal meaning per sentence.","Do not mix several modal verbs in one beginner item.","Use realistic school/home decisions."]},
  {stage:5,title:"Joining Ideas",goal:"Combine simple ideas with and, but, so, and because without run-ons or fragments.",parentNoteZh:"从单句过渡到复合表达，先掌握最常见的连接词。",advancement:"Student should connect two complete ideas and preserve tense/agreement.",promptMode:"Chinese prompt → one compound/complex sentence",sentenceMode:"1 sentence with 2 ideas",generationGuardrails:["Each item must require the named connector.","Both ideas should be easy enough that connector use is the real challenge.","Avoid stacking multiple connectors."]},
  {stage:6,title:"Time and Condition Clauses",goal:"Use when, before, after, and if to connect events and conditions.",parentNoteZh:"开始真正的从句训练，但句子仍保持短、清楚、可控。",advancement:"Student should handle clause order and basic comma placement in both clause orders.",promptMode:"Chinese prompt → one sentence with one subordinate clause",sentenceMode:"1 sentence, 2 clauses",generationGuardrails:["Exactly one target subordinating conjunction per item.","Alternate dependent-clause-first and main-clause-first structures.","Keep tense relationships obvious."]},
  {stage:7,title:"Wh- and Noun Clauses",goal:"Use what, how, where, and why clauses as parts of larger sentences.",parentNoteZh:"重点解决孩子容易混淆的 what/how/where/why 从句以及语序。",advancement:"Student should use statement word order inside embedded clauses.",promptMode:"Chinese prompt → one sentence containing a wh-clause",sentenceMode:"1 sentence, 8–16 words",generationGuardrails:["Avoid direct-question word order inside embedded clauses.","Use school/life situations where the clause has a clear function.","Do not introduce advanced relative clauses here."]},
  {stage:8,title:"Relative Clauses",goal:"Add identifying information with who, which, and that.",parentNoteZh:"学习 who/which/that 定语从句，让句子能自然增加人物或事物信息。",advancement:"Student should choose an appropriate relative word and avoid duplicated subjects.",promptMode:"Chinese prompt → one sentence with one relative clause",sentenceMode:"1 sentence, 9–18 words",generationGuardrails:["Use restrictive relative clauses first.","Keep antecedents concrete.","Avoid advanced comma-heavy nonrestrictive clauses until later review."]},
  {stage:9,title:"Sentence Expansion",goal:"Expand a basic sentence with useful time, place, manner, description, and reason details.",parentNoteZh:"从“写对一句”转向“把一句写具体”，但不堆砌无关修饰。",advancement:"Expanded sentences should stay grammatical, readable, and relevant.",promptMode:"Chinese idea + explicit detail requirement",sentenceMode:"1 rich sentence or 2 closely linked sentences",generationGuardrails:["Require specific detail types rather than vague 'make it longer'.","Do not reward unnecessary complexity.","Prefer precise familiar vocabulary over fancy vocabulary."]},
  {stage:10,title:"Connected Writing",goal:"Write 2–4 connected sentences with consistent tense, clear reference, and logical order.",parentNoteZh:"开始摆脱逐句翻译，练习句子之间的衔接。",advancement:"Student should maintain one topic across multiple sentences with clear pronoun reference and transitions.",promptMode:"Short Chinese/English situation → 2–4 English sentences",sentenceMode:"2–4 connected sentences",generationGuardrails:["Require one clear topic.","Specify number of sentences.","Do not provide sentence-by-sentence translations.","Require at least one transition or reference link when appropriate."]},
  {stage:11,title:"Paragraph Writing",goal:"Build a short paragraph with a topic sentence, supporting details, and a closing sentence.",parentNoteZh:"形成真正的段落结构：主题句、细节、结尾，并开始练习修改。",advancement:"Student should independently produce coherent 5–7 sentence paragraphs on familiar topics.",promptMode:"Mostly English prompt with optional Chinese support",sentenceMode:"5–7 sentence paragraph",generationGuardrails:["Give one clear writing purpose.","Ask for a topic sentence and 2–4 supporting details.","Do not over-scaffold every sentence.","Keep expected vocabulary at middle-school ESL level."]},
  {stage:12,title:"School Writing",goal:"Respond independently to common middle-school writing tasks.",parentNoteZh:"最终目标：英语题目直接写，覆盖解释、叙事、比较、观点和基于课堂内容的短答。",advancement:"Ongoing maintenance stage; use performance trends rather than a single completion threshold.",promptMode:"English-first school-style prompt",sentenceMode:"Paragraph or short constructed response",generationGuardrails:["Prompt should resemble real Grade 6 school work.","Require organization and relevant support, not sophisticated vocabulary.","Do not invent source evidence unless a source is provided.","Separate writing quality from factual subject-matter correctness when appropriate."]}
];

const L=(id,stage,skillId,order,title,objective,rules,commonErrors,promptPatterns,requiredElements,avoid,difficulty)=>({
  id,stage,skillId,order,title,objective,rules,commonErrors,promptPatterns,requiredElements,avoid,difficulty
});

export const CURRICULUM_LESSONS = [
  L("s1_sentence_core",1,"sentence_structure",1,"Complete sentence core","Build a complete Subject + Verb + Object/Complement sentence.",
    ["Every sentence needs a clear subject and finite verb.","Keep normal English word order: subject before verb.","Do not omit the subject even when Chinese can."],
    ["missing subject","missing verb","Chinese word order","fragment"],
    ["我每天做作业。","我的朋友喜欢科学课。","这本书很有趣。"],
    ["one complete clause","familiar noun/verb","no subordinate clause"],
    ["questions","rare vocabulary","two independent clauses"],"Very easy; 5–9 words."),

  L("s1_be_present",1,"be_verbs",2,"am / is / are","Use the correct present form of be with singular and plural subjects.",
    ["I → am.","he/she/it/singular noun → is.","you/we/they/plural noun → are."],
    ["I is","they is","plural noun + is","omitting be before adjective"],
    ["我今天很累。","这两本书很重。","我的老师很友好。"],
    ["adjective or noun complement","clear subject number"],
    ["past time","there is/are","continuous tense"],"Easy; 5–10 words."),

  L("s1_pronoun_subject_object",1,"pronouns",3,"Subject and object pronouns","Choose I/me, he/him, she/her, we/us, they/them by sentence position.",
    ["Subject pronouns perform the action.","Object pronouns receive the action or follow a preposition.","Do not use object forms as normal subjects."],
    ["Me like math","teacher helped we","with he"],
    ["老师帮助了我。","他们和我们一起学习。","她每天给他打电话。"],
    ["one obvious pronoun contrast"],
    ["possessive pronouns","relative pronouns","ambiguous antecedents"],"Easy; 6–11 words."),

  L("s1_noun_number",1,"singular_plural",4,"Singular, plural, and agreement","Match noun number with determiners and verbs.",
    ["Use plural nouns after numbers greater than one.","this/that are singular; these/those are plural.","Plural subjects take are and usually base-form present verbs."],
    ["two book","these book","books is","one pencils"],
    ["这两个苹果很大。","那些学生每天走路上学。","我有三本新书。"],
    ["clear quantity or demonstrative"],
    ["irregular plurals beyond common words","mass nouns"],"Easy; 6–11 words."),

  L("s1_articles_a_an",1,"articles",5,"a / an with one nonspecific thing","Use a/an before a singular count noun when introducing one nonspecific item.",
    ["a before consonant sound; an before vowel sound.","A/an is for one singular count noun.","Do not put a/an before plural nouns."],
    ["I have book","an dog","a apples","a homework"],
    ["我有一支新铅笔。","她吃了一个苹果。","他想买一把雨伞。"],
    ["singular count noun","clear first mention"],
    ["the as main target","uncountable edge cases"],"Easy; 6–10 words."),

  L("s1_articles_the_zero",1,"articles",6,"the vs no article","Use the for a specific known noun and no article for common general plurals/uncountables.",
    ["Use the when both speaker and listener can identify the thing.","General plural nouns often take no article.","School subjects and many meals often take no article."],
    ["the math as school subject","the dogs are friendly when dogs means dogs generally","missing the for a specific classroom object"],
    ["请关上门。","我喜欢数学。","狗通常喜欢玩。"],
    ["clear specific/general contrast"],
    ["geographic article exceptions","advanced institutional uses"],"Easy–moderate; 6–11 words."),

  L("s2_present_habits",2,"present_simple",1,"Habits and routines","Use simple present for repeated actions and routines.",
    ["Use base verb with I/you/we/they.","Use clear routine markers when helpful.","Do not use present progressive for a normal habit unless intended."],
    ["I am go every day","I going every day","past tense with every day"],
    ["我每天七点起床。","我们周五上体育课。","我放学后通常做作业。"],
    ["habit/routine meaning","present-time marker in many items"],
    ["one-time past events","future plans"],"Easy; 6–12 words."),

  L("s2_third_person_s",2,"third_person",2,"Third-person singular -s","Use verb-s/-es with he, she, it, or one singular person/thing.",
    ["he/she/it + verb-s in affirmative simple present.","After does/doesn't, return to base verb.","Watch common forms: goes, does, has."],
    ["she walk","he have","doesn't goes"],
    ["我妹妹每天坐公交车上学。","他的老师每天检查作业。","这家商店九点开门。"],
    ["singular third-person subject","affirmative form in most items"],
    ["complex clauses","uncommon spelling exceptions"],"Easy–moderate; 6–12 words."),

  L("s2_present_negative_question",2,"present_simple",3,"do / does negatives and questions","Use do/does and don't/doesn't with the base verb.",
    ["do/does carries tense.","Main verb stays in base form after do/does.","Use does with third-person singular."],
    ["doesn't likes","do he","does she goes"],
    ["他不喜欢辣的食物。","你每天走路上学吗？","她周末做作业吗？"],
    ["negative or yes/no question","base verb after auxiliary"],
    ["did","wh embedded clauses"],"Moderate; 6–13 words."),

  L("s2_frequency_position",2,"frequency",4,"Frequency adverbs","Place always, usually, often, sometimes, and never naturally.",
    ["Usually place frequency adverbs before a normal verb.","Place them after be.","Sometimes can also begin or end a sentence."],
    ["I go always","she always is late","double negatives with never"],
    ["我通常在家吃早餐。","他上课从不迟到。","我们有时放学后打篮球。"],
    ["one frequency adverb","simple present"],
    ["hardly/scarcely","multiple adverbs"],"Moderate; 7–13 words."),

  L("s2_present_mixed",2,"present_simple",5,"Present-time mixed control","Combine present tense, third-person agreement, articles, and frequency without adding new grammar.",
    ["Preserve all previously learned sentence-foundation rules.","Treat tense and agreement as separate checks."],
    ["correct verb but wrong article","correct tense but missing subject","third-person error hidden in longer sentence"],
    ["我的朋友通常在图书馆做作业。","这位老师每天给我们一个小测验。","我们周末经常去公园。"],
    ["at least two earlier skills","one sentence only"],
    ["clauses","advanced vocabulary"],"Moderate; 8–14 words."),

  L("s3_past_regular",3,"past_simple",1,"Regular past verbs","Use -ed forms for completed past actions.",
    ["Past time requires past verb in affirmative clauses.","Regular verbs normally add -ed/-d.","Use a clear past marker in early practice."],
    ["finish instead of finished","double past marking","using did + past verb"],
    ["我昨天完成了科学作业。","我们上周参观了博物馆。","她昨晚打扫了房间。"],
    ["yesterday/last.../ago","regular verb"],
    ["irregular verb as primary target","past perfect"],"Easy–moderate; 6–12 words."),

  L("s3_past_irregular",3,"past_simple",2,"Common irregular past verbs","Use common irregular past forms in context.",
    ["Memorize high-frequency forms: went, saw, ate, had, made, took, got, came, read.","Do not add -ed to an irregular past form."],
    ["goed","eated","taked","readed"],
    ["我们昨天去了图书馆。","我早上吃了一个苹果。","她上周看见了她的朋友。"],
    ["one high-frequency irregular verb","past-time marker"],
    ["rare irregular verbs","perfect tenses"],"Moderate; 6–12 words."),

  L("s3_past_be",3,"be_verbs",3,"was / were","Use was/were with past descriptions and locations.",
    ["I/he/she/it/singular noun → was.","you/we/they/plural noun → were.","Do not combine was/were with a simple past main verb unless grammatically needed."],
    ["they was","I were","was went"],
    ["我昨天很累。","他们昨天下午在体育馆。","那两本书在桌子上。"],
    ["past be meaning","clear subject number"],
    ["past progressive","passive voice"],"Moderate; 6–11 words."),

  L("s3_did_base",3,"did_auxiliary",4,"did / didn't + base verb","Use did/didn't for past questions and negatives with the base form.",
    ["did/didn't carries past tense.","Main verb must be base form after did/didn't.","Use did for all subjects."],
    ["didn't went","did she ate","didn't watched"],
    ["他昨天没有看电视。","你昨晚完成作业了吗？","我们没有错过公交车。"],
    ["past question or negative","base verb after did"],
    ["was/were questions as primary target","perfect tense"],"High priority; repeat often."),

  L("s3_past_sequence",3,"past_simple",5,"Two past actions in order","Describe two completed actions in a clear order using simple connectors.",
    ["Keep both completed actions in an appropriate past form.","Use then/after that only as a light sequencing aid.","Do not introduce complex time clauses yet."],
    ["first verb past, second verb present","unnecessary did","run-on without connector/punctuation"],
    ["我做完作业，然后玩了二十分钟游戏。","她吃完晚饭，然后给朋友打了电话。"],
    ["two simple past actions","one basic connector"],
    ["before/after clauses","long narratives"],"Moderate; 10–16 words."),

  L("s4_future_will",4,"future",1,"will + base verb","Use will for predictions, decisions, and straightforward future statements.",
    ["will + base verb for every subject.","Do not add -s or past tense after will.","Use a future-time marker in early items."],
    ["will goes","will went","will to go"],
    ["我们明天会考试。","我今晚会给你打电话。","天气明天会变冷。"],
    ["future marker","will + base verb"],
    ["future perfect","conditional would"],"Easy–moderate; 6–12 words."),

  L("s4_going_to",4,"future",2,"be going to","Use be going to for plans or evidence-based expectations.",
    ["Subject + correct be + going to + base verb.","Choose am/is/are based on subject.","Keep going to intact."],
    ["I going to","she are going to","going to went"],
    ["我周六打算去图书馆。","他们今晚打算做披萨。","她打算参加机器人俱乐部。"],
    ["clear plan meaning","correct be form"],
    ["gonna","future perfect"],"Moderate; 7–13 words."),

  L("s4_can_ability",4,"modals",3,"can / can't","Express ability and simple permission with can/can't + base verb.",
    ["can/can't + base verb.","No to after can.","No third-person -s after can."],
    ["can to swim","can swims","can't went"],
    ["他会弹钢琴。","我今天不能留下来。","我们可以在这里坐吗？"],
    ["can/can't meaning","base verb"],
    ["could have","modal perfect"],"Easy; 5–11 words."),

  L("s4_should_must",4,"modals",4,"should / must","Give advice with should and strong obligation with must.",
    ["should/must + base verb.","Use should for advice; must for strong necessity/rules.","Do not add to after the modal."],
    ["should to study","musts","must studied"],
    ["你应该早点睡觉。","学生必须带上校卡。","你应该先检查答案。"],
    ["clear advice vs obligation"],
    ["legal nuance","have got to","modal perfect"],"Moderate; 6–12 words."),

  L("s5_and",5,"coordination",1,"and for addition","Join two related ideas with and.",
    ["Both parts should make logical sense together.","Keep tense consistent unless meaning requires a change.","Avoid unnecessary repetition of the same subject when a natural shared subject works."],
    ["comma splice without and","two unrelated ideas","tense mismatch"],
    ["我做完作业，并且收拾了书包。","她喜欢数学，也喜欢科学。"],
    ["two related ideas","and"],
    ["three or more clauses","because/so as hidden target"],"Moderate; 10–16 words."),

  L("s5_but",5,"coordination",2,"but for contrast","Use but to connect contrasting ideas.",
    ["The two ideas should genuinely contrast.","Keep each side grammatically complete enough for the intended structure."],
    ["using and when contrast is needed","fragment after but","illogical contrast"],
    ["这本书很难，但是很有趣。","我很累，但是我还是完成了作业。"],
    ["clear contrast","but"],
    ["although","however"],"Moderate; 10–17 words."),

  L("s5_so",5,"coordination",3,"so for result","Use so to connect a cause with its result.",
    ["First idea gives the cause/background; second gives the result.","Do not use because and so redundantly in the same beginner sentence."],
    ["because...so double connector","reversed cause/result","fragment"],
    ["下雨了，所以我们待在室内。","我忘了带午饭，所以我买了学校午餐。"],
    ["clear cause → result relationship","so"],
    ["therefore","complex causal chains"],"Moderate; 10–17 words."),

  L("s5_because",5,"because",4,"because for reason","Use because to give a reason for an idea.",
    ["because introduces the reason.","Main idea and reason should both be clear.","Do not write a because-fragment by itself."],
    ["Because I was tired. as complete answer","because/so together","reason does not explain main idea"],
    ["我喜欢科学，因为我喜欢做实验。","我昨天早点睡了，因为我很累。"],
    ["main idea + because + reason"],
    ["because of","advanced causal clauses"],"High priority; 10–18 words."),

  L("s6_when",6,"time_clauses",1,"when clauses","Connect two events with when.",
    ["Use statement word order in both clauses.","Match tense to the intended time relationship.","If the when-clause comes first, use a comma in school-style writing."],
    ["question word order after when","tense mismatch","missing main clause"],
    ["当我到家时，我先做作业。","当老师提问时，我会举手。"],
    ["one when-clause","clear event relationship"],
    ["while/as soon as","multiple subordinate clauses"],"Moderate; 11–18 words."),

  L("s6_before_after",6,"time_clauses",2,"before / after","Show event order with before or after.",
    ["The connector itself shows sequence; verb tense must still be sensible.","Practice both clause orders.","Use comma when the dependent clause comes first."],
    ["reversed event meaning","two unrelated actions","missing comma in clause-first form"],
    ["我睡觉前会刷牙。","吃完晚饭后，我开始做作业。"],
    ["before or after","two clearly ordered events"],
    ["perfect aspect","until/unless"],"Moderate; 11–18 words."),

  L("s6_if_real",6,"if_clause",3,"Real if conditions","Use if for realistic conditions and results.",
    ["Use simple present in the if-clause for basic future conditions.","Main clause can use will/can/imperative as appropriate.","Do not normally use will directly after if in this beginner pattern."],
    ["If it will rain...","missing result clause","unreal conditional forms mixed in"],
    ["如果明天下雨，我们会待在家里。","如果你需要帮助，可以问老师。"],
    ["one realistic condition","clear result"],
    ["would/could unreal conditionals","unless"],"Moderate; 11–18 words."),

  L("s6_clause_order",6,"time_clauses",4,"Clause order and comma control","Move a time/condition clause before or after the main clause without changing meaning.",
    ["Dependent clause first → comma after it.","Main clause first → usually no comma before a short dependent clause.","Do not create sentence fragments."],
    ["comma missing in clause-first form","unnecessary comma in simple main-first form","fragment"],
    ["完成作业后，我会看电视。","我会看电视，等我完成作业以后。"],
    ["explicit clause-order target","same basic meaning in either order"],
    ["semicolon","advanced punctuation"],"Moderate; punctuation-focused."),

  L("s7_what_clause",7,"wh_clauses",1,"what clauses","Use what + subject + verb as a noun-like clause.",
    ["Embedded clause uses statement order, not direct-question order.","The what-clause must have a clear role in the larger sentence."],
    ["I know what is he doing","missing main clause","using that when what is needed"],
    ["我知道老师想要什么。","请告诉我你需要什么。"],
    ["main clause + what-clause","statement order"],
    ["relative what edge cases","very abstract verbs"],"Moderate–hard; 9–16 words."),

  L("s7_how_clause",7,"wh_clauses",2,"how clauses","Use how to express method, manner, or degree inside a larger sentence.",
    ["Use statement order in embedded clauses.","Choose how when the meaning is method/manner, not thing/place."],
    ["how do I... inside embedded clause","what/how confusion"],
    ["我知道怎么打开这个文件。","老师向我们展示了如何解决这个问题。"],
    ["clear method meaning","main clause + how-clause"],
    ["how much/how many as main focus","advanced infinitive distinctions"],"Moderate–hard."),

  L("s7_where_why_clause",7,"wh_clauses",3,"where / why clauses","Use where for place information and why for reason information in embedded clauses.",
    ["Embedded clauses keep statement order.","Choose connector by meaning: place vs reason."],
    ["where is the book after I know","why/where confusion","missing subject"],
    ["我不知道我的笔在哪里。","她解释了为什么她迟到了。"],
    ["embedded place or reason clause"],
    ["direct questions as target","relative where"],"Moderate–hard."),

  L("s7_embedded_question_mix",7,"wh_clauses",4,"Embedded-question word order","Distinguish direct-question order from embedded statement order.",
    ["Direct: Where is he? Embedded: I know where he is.","Do not invert subject and verb inside an embedded question.","Do-support usually disappears inside the embedded clause."],
    ["I know where does he live","Tell me what did she say","I wonder where is it"],
    ["我想知道他住在哪里。","你能告诉我她为什么离开吗？"],
    ["embedded wh-clause after know/tell/wonder"],
    ["whether/if embedded yes-no questions","formal inversion"],"Hard; high-value grammar target."),

  L("s8_who_relative",8,"relative_clauses",1,"who for people","Add identifying information about a person with who.",
    ["Antecedent is a person.","who acts as subject/object inside the relative clause as appropriate.","Do not repeat the person with another pronoun inside the clause."],
    ["the boy who he...","who for objects","missing antecedent"],
    ["帮助我的老师很友好。","赢得比赛的女孩是我的朋友。"],
    ["person antecedent","one restrictive who-clause"],
    ["whom","nonrestrictive commas"],"Moderate–hard."),

  L("s8_which_that",8,"relative_clauses",2,"which / that for things","Add identifying information about a thing using which or that.",
    ["Use that/which for things in these restrictive clauses.","Do not repeat it inside the relative clause.","Keep the antecedent immediately clear."],
    ["the book that it...","who for object","dangling antecedent"],
    ["我昨天买的书很有趣。","我们使用的电脑很旧。"],
    ["thing antecedent","one restrictive relative clause"],
    ["nonrestrictive which","preposition + which"],"Moderate–hard."),

  L("s8_relative_choice",8,"relative_clauses",3,"Choose who / which / that","Choose the relative word from the antecedent and sentence meaning.",
    ["Person → usually who/that.","Thing → which/that.","Avoid duplicated subject/object pronouns."],
    ["connector chosen by Chinese translation instead of antecedent","duplicate pronoun"],
    ["住在隔壁的人是一名老师。","桌子上的那台电脑是我的。"],
    ["clear antecedent type","one relative clause"],
    ["whose","where as relative adverb"],"Hard; transfer practice."),

  L("s9_time_place_detail",9,"sentence_expansion",1,"Add time and place details","Expand a plain sentence with relevant time and place information.",
    ["Add details that answer when/where.","Place details where they sound natural.","Do not change the main meaning."],
    ["detail in unnatural position","too many locations","tense changed accidentally"],
    ["把“我做作业”扩展成包含时间和地点的一句话。","把“我们练习篮球”写得更具体，加入什么时候和在哪里。"],
    ["explicit time detail","explicit place detail"],
    ["new clause grammar as main challenge","fancy adjectives"],"Moderate; 10–18 words."),

  L("s9_description",9,"sentence_expansion",2,"Add useful description","Add one or two meaningful adjective/adverb details without making the sentence unnatural.",
    ["Details should help the reader picture or understand the event.","Adjectives describe nouns; adverbs often describe actions.","Prefer specific common words."],
    ["random adjective stacking","adjective/adverb confusion","meaningless intensifiers"],
    ["把“我看见一只狗”扩展得更具体。","把“她说话”写得更具体，加入一个合适的方式细节。"],
    ["1–2 relevant descriptive details"],
    ["literary vocabulary","more than two new modifiers"],"Moderate."),

  L("s9_prepositional_detail",9,"sentence_expansion",3,"Prepositional detail","Use common prepositional phrases to add location, time, or relationship details.",
    ["Use common prepositions naturally: in, on, at, after, before, with, for.","Choose preposition by meaning rather than direct Chinese mapping."],
    ["in Monday","at the morning","with to my friend"],
    ["把“我和朋友学习”扩展成包含地点的一句话。","把“我们周一有数学课”写得更自然。"],
    ["one useful prepositional phrase"],
    ["idiomatic rare prepositions","phrasal verbs"],"Moderate."),

  L("s9_reason_purpose_detail",9,"sentence_expansion",4,"Add reason or purpose","Add a clear because or to-purpose detail to make a sentence more informative.",
    ["Use because + clause for reason.","Use to + base verb for simple purpose.","Do not confuse reason with result."],
    ["because fragment","to + past verb","reason that does not explain action"],
    ["把“我去了图书馆”扩展成包含原因的一句话。","把“她早起”扩展成包含目的的一句话。"],
    ["one reason or purpose detail"],
    ["so that","complex infinitive structures"],"Moderate–hard."),

  L("s10_two_sentence_link",10,"connected_writing",1,"Two connected sentences","Write two sentences about one event/topic with a clear logical link.",
    ["Sentence 2 must add, explain, contrast, or continue Sentence 1.","Keep tense consistent.","Avoid repeating the full noun unnecessarily."],
    ["two unrelated sentences","tense shift","repeating same sentence in different words"],
    ["用两句话写你昨天放学后做了什么。","用两句话描述一节你喜欢的课。"],
    ["exactly 2 sentences","one topic","logical connection"],
    ["sentence-by-sentence Chinese translation","paragraph length"],"2 sentences, 16–30 total words."),

  L("s10_reference",10,"connected_writing",2,"Pronoun reference across sentences","Use pronouns or repeated key nouns so the reader can tell what each sentence refers to.",
    ["Pronoun antecedent must be clear.","Avoid switching he/she/it/they ambiguously.","Use a noun again if a pronoun would be unclear."],
    ["ambiguous it/they","wrong pronoun gender/number","every sentence starts with same noun"],
    ["写两到三句话介绍你的一位老师，并使用代词衔接。","写两句话介绍一本书，第二句用代词自然衔接。"],
    ["2–3 sentences","clear reference"],
    ["multiple characters with ambiguous pronouns"],"2–3 sentences."),

  L("s10_transition",10,"connected_writing",3,"Basic transitions","Connect ideas with simple transitions such as first, then, also, however, because, so.",
    ["Choose transition by logical relationship.","Do not use a transition just because the prompt names it.","Punctuation must remain simple and correct."],
    ["however used for addition","then used without sequence","transition comma errors"],
    ["用三句话描述你早上的准备过程，使用至少一个顺序连接词。","用三句话介绍一个爱好，并使用 also 或 because 衔接。"],
    ["3 sentences","at least one appropriate transition"],
    ["formal academic transitions list","too many transitions"],"3 sentences, 25–45 words."),

  L("s10_mini_paragraph",10,"connected_writing",4,"Three- to four-sentence mini-paragraph","Write a focused mini-paragraph with a beginning idea and supporting sentences.",
    ["Stay on one topic.","Sentence order should make sense.","Final sentence may close or add a final detail."],
    ["topic drift","list of unrelated facts","same sentence pattern repeated"],
    ["用3到4句话写一次你在学校解决问题的经历。","用3到4句话介绍你最喜欢的一门课以及原因。"],
    ["3–4 sentences","one clear topic","at least one support/detail sentence"],
    ["five-paragraph essay language","advanced thesis"],"3–4 sentences, 35–60 words."),

  L("s11_topic_sentence",11,"paragraph",1,"Topic sentence","Open a paragraph with a sentence that clearly states the main idea.",
    ["Topic sentence should be broad enough for supporting details.","Do not put every detail in the first sentence.","It should match the actual paragraph topic."],
    ["too specific","vague 'I have many things'","topic sentence unrelated to details"],
    ["写一个主题句，准备介绍为什么你喜欢科学课。","写一个主题句，准备介绍一个让你印象深刻的周末。"],
    ["one topic sentence plus 2 planning details"],
    ["thesis terminology","complex hook requirements"],"Planning + 1 sentence."),

  L("s11_supporting_details",11,"paragraph",2,"Supporting details","Develop a topic with specific examples, reasons, or facts.",
    ["Every supporting sentence should connect to the topic sentence.","Specific details are stronger than vague repetition.","Use transitions only when useful."],
    ["repeating topic sentence","off-topic detail","unsupported opinion"],
    ["围绕“我喜欢机器人俱乐部”写4到5句话，并给出至少两个具体细节。","围绕“我在学校最喜欢的地方”写一个短段落。"],
    ["4–5 sentences","topic + at least 2 concrete details"],
    ["research facts not provided","advanced rhetorical devices"],"4–5 sentences, 50–80 words."),

  L("s11_sequence_paragraph",11,"paragraph",3,"Sequence paragraph","Organize events or steps in chronological/logical order.",
    ["Use first/next/then/finally only when they help.","Keep tense consistent.","Each sentence should move the sequence forward."],
    ["out-of-order events","tense switches","transition overload"],
    ["用5句话写你放学回家后的流程。","用5到6句话描述你做一个简单项目的步骤。"],
    ["5–6 sentences","clear sequence","consistent tense"],
    ["complex procedural vocabulary"],"5–6 sentences."),

  L("s11_conclusion_revision",11,"paragraph",4,"Closing and revision","End a paragraph naturally and revise for grammar, repetition, and clarity.",
    ["Closing sentence should fit the main idea without merely copying the topic sentence.","Revision checks: subject/verb, tense, articles, punctuation, repeated words.","Prefer one meaningful revision over cosmetic complexity."],
    ["copying topic sentence exactly","adding a new unrelated idea at the end","editing grammar into worse form"],
    ["给一个5句短段落写合适的结尾句。","写一个5到6句段落，并在完成后检查时态、冠词和重复。"],
    ["5–6 sentences","clear closing sentence","self-revision target"],
    ["formal essay conclusion phrases"],"5–6 sentences, revision-focused."),

  L("s12_constructed_response",12,"school_writing",1,"Short constructed response","Answer a school-style question directly, then support the answer with relevant explanation.",
    ["First sentence should answer the question.","Add 1–3 supporting sentences.","Do not wander away from the prompt."],
    ["answer hidden until last sentence","unsupported one-word answer","off-topic detail"],
    ["Why is teamwork useful during a science project? Write 3–4 sentences.","Explain one reason school rules can help students. Write 3–4 sentences."],
    ["3–4 sentences","direct answer","at least one explanation/example"],
    ["requiring outside facts","advanced essay structure"],"English prompt; 3–4 sentences."),

  L("s12_narrative_response",12,"school_writing",2,"Short narrative response","Write a short beginning-middle-end account of a familiar event.",
    ["Use a consistent past tense unless intentionally shifting.","Include sequence and one useful detail.","Keep the event focused enough for a short response."],
    ["list of events with no connection","random tense shifts","too much background"],
    ["Write 5–6 sentences about a time you solved a problem at school.","Describe a time you learned something from a mistake."],
    ["5–6 sentences","past tense","clear event sequence"],
    ["fiction world-building","long dialogue"],"English prompt; 5–6 sentences."),

  L("s12_explanatory_response",12,"school_writing",3,"Explanatory writing","Explain how or why something works using organized steps or reasons.",
    ["Define the main idea in simple language.","Organize reasons/steps logically.","Use examples when they help."],
    ["only listing without explanation","cause/result confusion","unsupported technical claims"],
    ["Explain how you prepare for a math test in 5–6 sentences.","Explain why practice can improve a skill."],
    ["5–6 sentences","logical explanation","one example or specific detail"],
    ["specialized facts not given"],"English prompt; 5–6 sentences."),

  L("s12_compare_contrast",12,"school_writing",4,"Compare and contrast","State at least one similarity and one difference clearly.",
    ["Use both/all, but, while, however, unlike, or similar simple signals appropriately.","Compare the same feature on both sides.","Do not just write two unrelated descriptions."],
    ["only similarities","only differences","different comparison categories"],
    ["Compare studying at home and studying at school in 5–6 sentences.","Compare two school subjects you know well."],
    ["5–6 sentences","at least one similarity","at least one difference"],
    ["formal block/point-by-point terminology"],"English prompt; 5–6 sentences."),

  L("s12_opinion_support",12,"school_writing",5,"Opinion with support","State an opinion and support it with clear reasons/examples.",
    ["Opinion must be explicit.","Give at least two relevant reasons or one reason plus a concrete example.","Avoid claims requiring evidence the student does not have."],
    ["opinion without reasons","repeating same reason","irrelevant example"],
    ["Should students have more time for clubs after school? Write 5–6 sentences and support your opinion.","Which is more useful for learning: working alone or with a partner? Explain your view."],
    ["5–6 sentences","clear opinion","relevant support"],
    ["political topics","controversial adult issues","research citations"],"English prompt; 5–6 sentences.")
];

export const lessonMap=Object.fromEntries(CURRICULUM_LESSONS.map(x=>[x.id,x]));
export const lessonsBySkill=Object.fromEntries(
  [...new Set(CURRICULUM_LESSONS.map(x=>x.skillId))].map(skillId=>[
    skillId,
    CURRICULUM_LESSONS.filter(x=>x.skillId===skillId).sort((a,b)=>a.stage-b.stage||a.order-b.order)
  ])
);
